server:
  port: 30204

spring:
  application:
    name: demo-flink
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.data:
  flink:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local